version: '3.8'

services:
  servicio-banco-lp1:
    build: ./servicio-banco-lp1
    depends_on:
      - bd1
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bd1:5432/shibasito
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - shibasito_network

  servicio-reniec-lp2:
    build: ./servicio-reniec-lp2
    depends_on:
      - bd2
      - rabbitmq
    environment:
      - DATABASE_URL=mysql+pymysql://root:pass@bd2/reniec
      - RABBITMQ_HOST=rabbitmq
    networks:
      - shibasito_network

  terraform:
    build: ./terraform
    volumes:
      - ./terraform:/terraform
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /terraform
    networks:
      - shibasito_network

networks:
  shibasito_network:
    external: true
