global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'servicio-banco-lp1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['servicio-banco-lp1:8080']

  - job_name: 'servicio-reniec-lp2-api'
    static_configs:
      - targets: ['servicio-reniec-lp2:8000']

  - job_name: 'servicio-reniec-lp2-consumer'
    static_configs:
      - targets: ['servicio-reniec-lp2:8001']
